### Python modules
import os, re
from pathlib import Path

### Configuration
configfile: "../config/config.yaml"

# Directories
ENV_DIR = srcdir("../envs")
READS_DIR = config["reads_dir"]
RESULTS_DIR = config["results_dir"]
DATABASES_DIR = config["databases_dir"]

# Sample variables
SAMPLES = list(glob_wildcards(os.path.join(READS_DIR, "{sample}_R1_001.fastq.gz")))[0]
SAMPLES_NO_CONTROLS = list(filter(lambda elmt: "neg" not in elmt, SAMPLES))

SAMPLES_VIR = SAMPLES_NO_CONTROLS

#COASSEMBLIES = list(set([re.sub(r'_S\d', '', sample) for sample in SAMPLES]))
#COASSEMBLIES_NO_CONTROLS = list(filter(lambda elmt: "Control" not in elmt, COASSEMBLIES))
#COASSEMBLIES_MAG = list(filter(lambda elmt: "T6_Water" not in elmt, COASSEMBLIES_NO_CONTROLS))

### Rules to include
# Function to recursively include all .smk files
def include_smk_files(directory):
    for root, _, files in os.walk(directory):
        files.sort()
        for file in files:
            if file.endswith('.smk'):
                include: os.path.join(root, file)

# Include all .smk files from the rules directory and subdirectories
include_smk_files('rules/')

