### TO-MODIFY: Location of directories
reads_dir: "/work/river/Sentinel/RNA/sequences/"
results_dir: "/scratch/boutroux/BioVir_RNA/"
databases_dir: "/work/river/Databases/"

### Threads
# Assembly
fastp:
  threads: 4
megahit:
  threads: 30

# Viral detection
vibrant:
  threads: 12
checkv:
  threads: 12
cobra:
  threads: 20
vrhyme:
  threads: 20
blast:
  threads: 4

# Coverage
minimap2:
  threads: 20
samtools:
  threads: 8
bedtools:
  threads: 4
coverm:
  threads: 30

# Taxonomy
genomad:
  threads: 8

